# Generated by Django 4.0.3 on 2022-04-09 21:46

import account.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('zeal_id', models.CharField(blank=True, max_length=16, null=True)),
                ('admission_no', models.CharField(max_length=16, unique=True)),
                ('fullname', models.CharField(max_length=128)),
                ('college', models.CharField(max_length=128)),
                ('contact_no', models.CharField(max_length=10, unique=True, validators=[account.validators.validate_contact_number])),
            ],
        ),
    ]
