# Generated by Django 4.0.3 on 2022-04-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zeal_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
