# Generated by Django 4.0.3 on 2022-04-11 19:09

import account.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_event_contact_alter_society_contact'),
        ('account', '0002_rename_user_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=10, unique=True, validators=[account.validators.validate_contact_number])),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.society')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
