# Generated by Django 4.0.3 on 2022-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='coupon_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='coupon_used',
            field=models.BooleanField(default=False),
        ),
    ]
