version: "3"

services:
  frontend:
    env_file: client/.env
    build:
      context: client
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - 3000:4050
  backend:
    restart: always
    build: .
    env_file: .env
    ports:
      - 8050:8050
    volumes:
      - type: volume
        source: database
        target: /zealicon/database/
    command: >
      bash -c "python3 manage.py migrate
      && python3 manage.py collectstatic --noinput
      && /usr/local/bin/gunicorn Zealicon.wsgi:application -b :8050"

volumes:
  database: