version: "3.8"

services:
    frontend:
        build:
            context: client
            dockerfile: Dockerfile
        env_file: client/.env
        ports:
            - 4050:80

    backend:
        restart: always
        build: .
        env_file: .env
        ports:
            - 8050:8050
        volumes:
            - type: volume
              source: database
              target: /zealicon/database/
        command: >
            bash -c "python3 manage.py migrate && python3 manage.py collectstatic --noinput && /usr/local/bin/gunicorn Zealicon.wsgi:application -b :8050"

    postgres:
        restart: always
        env_file: .env
        image: postgres:latest
        ports:
            - "5442:5442"
        volumes:
            - pgdbdata:/var/lib/postgresql/data/

volumes:
    database:
    pgdbdata:
